name: Weather Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  weather:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python bot.py
